### ISSUE TITLE
Error while running on linux

### ISSUE THREAD

**Issue by phadkesharan** [Ruslan-B/FFmpeg.AutoGen#307]
* **I'm submitting a ... **
  - [ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
 Report a bug
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1156()
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_449()
   at FFmpeg.AutoGen.ffmpeg.av_version_info()

* **What is the current behavior?**
Unable to run on linux .net 8.0 ubuntu 20.04

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

      //Program.cs
      using FFmpeg.AutoGen;
      
      
      ffmpeg.RootPath = "/usr/local/lib";
      
      Console.WriteLine(ffmpeg.av_version_info().ToString());

* **What is the expected behavior?**
The FFmpeg version should be displayed in the console

* **Please tell us about your environment:**
* // linux ubuntu 20.04 
// dotnet sdk 8.0
//nuget package :  FFmpeg.AutoGen --version 7.0.0
//ffmpeg version : 6.1.1 (installed using apt-get)

- version: 
version 7.0.0
Also same behavior with version 6.0.0 and version 6.1.0.1

**Comment by Ruslan-B** [comment]
most-probably you did but for such simple function looks like name bizarreries is unresolved besides if it is  6.1.1 - and you might used recent nuget you have install 6.1+ nuget package.

**Comment by Ruslan-B** [comment]
I'll move to questions repo in 24 hours there are a lot of linux users given there are support for 4.3 5.+ - major ones 6.1. 
And given you profile almost not traceable I cannot estimate your tech skills - if step here be ready you have to work hard.
